{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "ename": "RuntimeError",
     "evalue": "ERROR: unable to open image_naname/naname.xml for reading.",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mRuntimeError\u001b[0m                              Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-4-1aa230e03ea5>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     46\u001b[0m \u001b[0mtrain_xml_3\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m\"image_naname/naname.xml\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     47\u001b[0m \u001b[0msvm_file_3\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m\"model/naname_detector.svm\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 48\u001b[0;31m \u001b[0mdlib\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtrain_simple_object_detector\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtrain_xml_3\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0msvm_file_3\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0moptions\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     49\u001b[0m \u001b[0mdetector3\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mdlib\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msimple_object_detector\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msvm_file_3\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     50\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mRuntimeError\u001b[0m: ERROR: unable to open image_naname/naname.xml for reading."
     ]
    }
   ],
   "source": [
    "##裏と表の判別##マイナンバーカードに反応するようにする##\n",
    "# -*- coding: UTF-8 -*-\n",
    "#http://qiita.com/Algebra_nobu/items/a488fdf8c41277432ff3\n",
    "from skimage import io\n",
    "import cv2\n",
    "import os\n",
    "import sys\n",
    "import dlib\n",
    "import numpy as np\n",
    "#import cam\n",
    "sys.path.append(os.getcwd())\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.patches as patches\n",
    "\n",
    "#学習(train)\n",
    "\n",
    "options = dlib.simple_object_detector_training_options()\n",
    "# 学習時に画像の左右の反転を行うか\n",
    "options.add_left_right_image_flips = False\n",
    "# コストパラメータ\n",
    "options.C = 6\n",
    "# options.detection_window_size = 150 * 150    \n",
    "# options.epsilon = 0.01\n",
    "# スレッド数\n",
    "options.num_threads = 4\n",
    "# 学習中に詳細を表示するか\n",
    "options.be_verbose = True\n",
    "\n",
    "    #表面の検出\n",
    "#def front():\n",
    "train_xml_1 = \"data/image_front/front.xml\"\n",
    "svm_file_1 = \"model/front_detector.svm\"\n",
    "dlib.train_simple_object_detector(train_xml_1, svm_file_1, options)\n",
    "detector1 = dlib.simple_object_detector(svm_file_1)\n",
    "    \n",
    "    #裏面の検出\n",
    "#def back():\n",
    "train_xml_2 = \"data/image_back/back.xml\"\n",
    "svm_file_2 = \"model/back_detector.svm\"\n",
    "dlib.train_simple_object_detector(train_xml_2, svm_file_2, options)\n",
    "detector2 = dlib.simple_object_detector(svm_file_2)\n",
    "    \n",
    "    #斜めの検出\n",
    "#def naname():\n",
    "train_xml_3 = \"image_naname/naname.xml\"\n",
    "svm_file_3 = \"model/naname_detector.svm\"\n",
    "dlib.train_simple_object_detector(train_xml_3, svm_file_3, options)\n",
    "detector3 = dlib.simple_object_detector(svm_file_3)\n",
    "\n",
    "\n",
    "        \n",
    "        \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "##裏と表の判別##マイナンバーカードに反応するようにする##\n",
    "# -*- coding: UTF-8 -*-\n",
    "#http://qiita.com/Algebra_nobu/items/a488fdf8c41277432ff3\n",
    "from skimage import io\n",
    "import cv2\n",
    "import os\n",
    "import sys\n",
    "import dlib\n",
    "import numpy as np\n",
    "#import cam\n",
    "sys.path.append(os.getcwd())\n",
    "\n",
    "\n",
    "#学習(train)\n",
    "options = dlib.simple_object_detector_training_options()\n",
    "# 学習時に画像の左右の反転を行うか\n",
    "options.add_left_right_image_flips = False\n",
    "# コストパラメータ\n",
    "options.C = 3    \n",
    "options.detection_window_size = 150 * 150    \n",
    "options.epsilon = 0.01\n",
    "# スレッド数\n",
    "options.num_threads = 4\n",
    "# 学習中に詳細を表示するか\n",
    "options.be_verbose = True\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "#検出\n",
    "import dlib\n",
    "import cv2\n",
    "\n",
    "\n",
    "class MynumberDetector(object):\n",
    "    \n",
    "    def _init_(self):#constracta, self=instance\n",
    "        self.detector_front = dlib.fhog_object_detector(\"image_front/front_detector.svm\")\n",
    "        self.detector_back = dlib.fhog_object_detector(\"image_back/back_detector.svm\")\n",
    "        self.detector_naname = dlib.fhog_object_detector(\"image_naname/naname_detector.svm\")\n",
    "        \n",
    "        self.predictor_front = dlib.shape_predictor(\"image_front/front_predictor.dat\")\n",
    "        self.predictor_back = dlib.shape_predictor(\"image_back/back_predictor.dat\")\n",
    "        self.predictor_naname = dlib.shape_predictor(\"image_naname/naname_predictor.dat\")\n",
    "        \n",
    "    def detect_front(self, image, select_only_one = True):\n",
    "        img = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)\n",
    "        detectors = self.detector_front(img)\n",
    "        dets = [[x.left(), x.top(), x.right(), x.bottom()] for x in detectors]\n",
    "        \n",
    "        if select_only_one:\n",
    "            dets = dets[:1]#getindex[0-1]\n",
    "            \n",
    "        shapes = []\n",
    "        for i  in range(len(dets)):\n",
    "            d = detectors[i]\n",
    "            shape = self.predictor_front(img, d)\n",
    "            shape = [(p.x, p.y) for p in shape.parts()]\n",
    "            shapes.append(shape)#add\n",
    "            \n",
    "        return dets, shapes\n",
    "    \n",
    "    def detect_back(self, image, select_only_one = True):\n",
    "        img = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)\n",
    "        detectors = self.detector_front(img)\n",
    "        dets = [[x.left(), x.top(), x.right(), x.bottom()] for x in detectors]\n",
    "        \n",
    "        if select_only_one:\n",
    "            dets = dets[:1]#getindex[0-1]\n",
    "            \n",
    "        shapes = []\n",
    "        for i  in range(len(dets)):\n",
    "            d = detectors[i]\n",
    "            shape = self.predictor_front(img, d)\n",
    "            shape = [(p.x, p.y) for p in shape.parts()]\n",
    "            shapes.append(shape)#add\n",
    "            \n",
    "        return dets, shapes\n",
    "    \n",
    "    def detect_naname(self, image, select_only_one = True):\n",
    "        img = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)\n",
    "        detectors = self.detector_front(img)\n",
    "        dets = [[x.left(), x.top(), x.right(), x.bottom()] for x in detectors]\n",
    "        \n",
    "        if select_only_one:\n",
    "            dets = dets[:1]#getindex[0-1]\n",
    "            \n",
    "        shapes = []\n",
    "        for i  in range(len(dets)):\n",
    "            d = detectors[i]\n",
    "            shape = self.predictor_front(img, d)\n",
    "            shape = [(p.x, p.y) for p in shape.parts()]\n",
    "            shapes.append(shape)#add\n",
    "            \n",
    "        return dets, shapes\n",
    "    \n",
    "    \n",
    "    def detect_face():     \n",
    "        #顔の認識\n",
    "        f_cascade = cv2.CascadeClassifier('haarcascade_frontalface_alt2.xml')\n",
    "        #顔認識の実行\n",
    "        facerect = f_cascade.detectMultiScale(frame, scaleFactor=1.2, minNeighbors=10, minSize=(10, 10))\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "ename": "AttributeError",
     "evalue": "'MynumberDetector' object has no attribute 'detector_front'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-10-f6338883e6d1>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     39\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     40\u001b[0m \u001b[0;32mif\u001b[0m \u001b[0m__name__\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;34m'__main__'\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 41\u001b[0;31m     \u001b[0mmain\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m<ipython-input-10-f6338883e6d1>\u001b[0m in \u001b[0;36mmain\u001b[0;34m()\u001b[0m\n\u001b[1;32m     21\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     22\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 23\u001b[0;31m         \u001b[0mboxes\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mshapes\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mmynumber_det\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdetector_front\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mframe\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     24\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     25\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mlen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mboxes\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m>\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mAttributeError\u001b[0m: 'MynumberDetector' object has no attribute 'detector_front'"
     ]
    }
   ],
   "source": [
    "import cv2\n",
    "import numpy as np\n",
    "\n",
    "#import MynumberDetector\n",
    "#from lib.masker import mask_front_driver_license\n",
    "\n",
    "\n",
    "def main():\n",
    "    cam = cv2.VideoCapture(0)\n",
    "    if not cam.isOpened():\n",
    "        print(\"Unable to connect to camera.\")\n",
    "        return\n",
    "    _, sample_frame = cam.read()\n",
    "\n",
    "    mynumber_det = MynumberDetector()\n",
    "\n",
    "    while cam.isOpened():\n",
    "        frame_got, frame = cam.read()\n",
    "        if frame_got is False:\n",
    "            break\n",
    "\n",
    "\n",
    "        boxes, shapes = mynumber_det.detect_front(frame)\n",
    "\n",
    "        if len(boxes) > 0:\n",
    "            landmark_face = shapes[0][12:16]\n",
    "\n",
    "            # mask01 = frame.copy()\n",
    "            # secret = res['landmarks']['secret']\n",
    "            # cv2.fillPoly(mask01, [np.array([secret[0], secret[1], secret[3], secret[2]])], (0,0,0))\n",
    "            # cv2.imshow('mask01', mask01)\n",
    "\n",
    "            #mask02 = mask_front_mynumber(frame, landmark_face)\n",
    "            cv2.imshow('mask02', mask02)\n",
    "\n",
    "        cv2.imshow(\"Preview\", frame)\n",
    "        if cv2.waitKey(10) == 27:\n",
    "            break\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import sys\n",
    "import glob\n",
    "import dlib\n",
    "from skimage import io\n",
    "\n",
    "options = dlib.shape_predictor_training_options()\n",
    "options.oversampling_amount = 300\n",
    "options.nu = 0.05\n",
    "options.tree_depth = 2\n",
    "options.be_verbose = True\n",
    "\n",
    "training_xml_path = \"image_front/front.xml\"\n",
    "dlib.train_shape_predictor(training_xml_path, \"predictor.dat\", options)\n",
    "print(\"\\nTraining accuracy: {}\".format(\n",
    "    dlib.test_shape_predictor(training_xml_path, \"predictor.dat\")))\n",
    "\n",
    "testing_xml_path = \"image_front/front.xml\"\n",
    "print(\"Testing accuracy: {}\".format(\n",
    "    dlib.test_shape_predictor(testing_xml_path, \"predictor.dat\")))\n",
    "predictor = dlib.shape_predictor(\"predictor.dat\")\n",
    "detector = dlib.simple_object_detector(\"image_front/front_detector.svm\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "import os\n",
    "import dlib\n",
    "import glob\n",
    "from skimage import io\n",
    "import cv2\n",
    "\n",
    "\n",
    "detector = dlib.simple_object_detector(\"image_front/front_detector.svm\")\n",
    "predictor = dlib.shape_predictor(\"predictor.dat\")\n",
    "#win = dlib.image_window()\n",
    "\n",
    "\n",
    "frame = \"image_front/reF_20190806_0315*.jpg\"\n",
    "cv2.imread(frame)\n",
    "#リサイズ\n",
    "def scale_to_width(img, width):\n",
    "    scale = width / img.shape[1]\n",
    "    return cv2.resize(img, dsize=None, fx=scale, fy=scale)\n",
    "\n",
    "    frame = scale_to_width(frame, 480)\n",
    "\n",
    "for f in glob.glob(frame):\n",
    "    print(\"Processing file: {}\".format(f))\n",
    "    img = io.imread(f)\n",
    "\n",
    "    #win.clear_overlay()\n",
    "    #win.set_image(img)\n",
    "\n",
    "    dets = detector(img, 1)\n",
    "    \n",
    "    print(\"Number of faces detected: {}\".format(len(dets)))\n",
    "    for k, d in enumerate(dets):\n",
    "        print(\"Detection {}: Left: {} Top: {} Right: {} Bottom: {}\".format(\n",
    "            k, d.left(), d.top(), d.right(), d.bottom()))\n",
    "        # Get the landmarks/parts for the face in box d.\n",
    "        shape = predictor(img, d)\n",
    "        print(\"Part 0: {}, Part 1: {} ...\".format(shape.part(0),\n",
    "                                                  shape.part(1)))\n",
    "        # Draw the face landmarks on the screen.\n",
    "        #win.add_overlay(shape)\n",
    "        cv2.imwrite(\"reF_20190806_0315*.jpg\")\n",
    "\n",
    "    #win.add_overlay(dets)\n",
    "    #dlib.hit_enter_to_continue()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
